# HW 2: Wrangling

**Q1.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. Categorical variable: For the Minnesota police use of for data, `./data/mn_police_use_of_force.csv`, clean the `subject_injury` variable, handling the NA's; this gives a value `Yes` when a person was injured by police, and `No` when no injury occurred. What proportion of the values are missing? Is this a concern? Cross-tabulate your cleaned `subject_injury` variable with the `force_type` variable. Are there any patterns regarding when the data are missing?
3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.
4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [11]:
# 1
# Numeric variable: For ./data/airbnb_hw.csv, clean the Price variable as well as you can, and explain the choices you make.
# How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)

# First, import packages
import pandas as pd
import numpy as np

# Load data
airbnb = pd.read_csv('https://raw.githubusercontent.com/dylanmulieri/wrangling/refs/heads/main/assignment/data/airbnb_hw.csv')

# Create copy to work with
airbnb_df = airbnb.copy()

# Look at df
display(airbnb_df.head())
display(airbnb_df.info())
display(airbnb_df.describe())

# Clean 'Price'
display(airbnb_df['Price']) # look at price
display(airbnb_df['Price'].isna().sum()) # check for missing values
# Price contains no missing variables

# Search for "$" or " " or "," in Price
display(airbnb_df[airbnb_df['Price'].str.contains('$')])
display(airbnb_df[airbnb_df['Price'].str.contains(' ')])
display(airbnb_df[airbnb_df['Price'].str.contains(',')])

# Remove "," and " "
airbnb_df['Price'] = airbnb_df['Price'].str.replace(',', '')

# Check that they were removed
display(airbnb_df[airbnb_df['Price'].str.contains(' ')])
display(airbnb_df[airbnb_df['Price'].str.contains(',')])

'''
There were no NA values in 'Price' variable.
The only cleaning I had to do was removing " " and ",".
'''

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30478 entries, 0 to 30477
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30478 non-null  int64
 1   Host Since                  30475 non-null  object
 2   Name                        30478 non-null  object
 3   Neighbourhood               30478 non-null  object
 4   Property Type               30475 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30478 non-null  object
 7   Zipcode                     30344 non-null  float64
 8   Beds                        30393 non-null  float64
 9   Number of Records           30478 non-null  int64
 10  Number Of Reviews           30478 non-null  int64
 11  Price                       30478 non-null  object
 12  Review Scores Rating        22155 non-null  float64
dtypes: float64(4), int64(3), object(6)
memory usage: 3.0+ MB

None

,Host Id,Review Scores Rating (bin),Zipcode,Beds,Number of Records,Number Of Reviews,Review Scores Rating
count,3.047800e+04,22155.000000,30344.000000,30393.000000,30478.0,30478.000000,22155.000000
mean,1.273171e+07,90.738659,10584.854831,1.530089,1.0,12.018735,91.993230
std,1.190270e+07,9.059519,921.299397,1.015359,0.0,21.980703,8.850373
min,5.000000e+02,20.000000,1003.000000,0.000000,1.0,0.000000,20.000000
25%,2.701298e+06,85.000000,10017.000000,1.000000,1.0,0.000000,89.000000
50%,8.551693e+06,90.000000,10065.000000,1.000000,1.0,3.000000,94.000000
75%,2.120617e+07,100.000000,11216.000000,2.000000,1.0,13.000000,100.000000
max,4.303307e+07,100.000000,99135.000000,16.000000,1.0,257.000000,100.000000

0        145
1         37
2         28
3        199
4        549
        ...
30473    300
30474    125
30475     80
30476     35
30477     80
Name: Price, Length: 30478, dtype: object

np.int64(0)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,43022976,8/31/2015,10 Mins to Time Square/two floors,Queens,Apartment,NaN,Entire home/apt,11101.0,5.0,1,0,300,NaN
30474,42993382,8/31/2015,"1BR ocean view & F,Q train st",Brooklyn,Apartment,NaN,Private room,11224.0,2.0,1,0,125,NaN
30475,43033067,8/31/2015,Amazing Private Room,Brooklyn,Other,NaN,Private room,11206.0,1.0,1,0,80,NaN
30476,43000991,8/31/2015,Charming private female room: UWS,Manhattan,Apartment,NaN,Private room,10025.0,1.0,1,0,35,NaN
30477,42999189,8/31/2015,Huge Beautiful Bedroom - Astoria,Queens,House,NaN,Private room,11105.0,1.0,1,0,80,NaN

Empty DataFrame
Columns: [Host Id, Host Since, Name, Neighbourhood , Property Type, Review Scores Rating (bin), Room Type, Zipcode, Beds, Number of Records, Number Of Reviews, Price, Review Scores Rating]
Index: []

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
101,8730,2/27/2009,Comfort & Convenience,Manhattan,Condominium,100.0,Entire home/apt,10003.0,6.0,1,4,"1,990",100.0
263,34915,8/30/2009,Luxurious 2-Floor Manhattan Mansion,Manhattan,Apartment,NaN,Entire home/apt,10075.0,2.0,1,0,"1,000",NaN
764,112879,4/23/2010,Modern Luxury Meets Old Money Charm,Brooklyn,Apartment,NaN,Entire home/apt,11206.0,5.0,1,0,"1,200",NaN
1272,214148,8/26/2010,"LARGE, COMFY 1BDR W/CHARACTER!!!",Brooklyn,Apartment,90.0,Entire home/apt,11216.0,1.0,1,30,"1,000",92.0
1275,213266,8/26/2010,Beautiful 1 Bedroom in Nolita/Soho,Manhattan,Apartment,75.0,Entire home/apt,10012.0,2.0,1,2,"5,000",76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28951,37155810,6/30/2015,Central Park Luxury : 115916,Manhattan,Apartment,NaN,Entire home/apt,10019.0,2.0,1,0,"3,390",NaN
28952,37155810,6/30/2015,Central Park South Place : 112756,Manhattan,Apartment,NaN,Entire home/apt,10019.0,1.0,1,0,"1,356",NaN
28953,37155810,6/30/2015,Central Park South Views : 112754,Manhattan,Apartment,NaN,Entire home/apt,10019.0,1.0,1,0,"2,599",NaN
28985,37241813,7/1/2015,VERY Spacious 3BR in East Village,Manhattan,Apartment,NaN,Entire home/apt,10009.0,3.0,1,0,"2,000",NaN
30281,42160989,8/21/2015,Luxury Duplex for Pope Visit,Brooklyn,Apartment,NaN,Entire home/apt,11211.0,4.0,1,0,"2,000",NaN

Empty DataFrame
Columns: [Host Id, Host Since, Name, Neighbourhood , Property Type, Review Scores Rating (bin), Room Type, Zipcode, Beds, Number of Records, Number Of Reviews, Price, Review Scores Rating]
Index: []

Empty DataFrame
Columns: [Host Id, Host Since, Name, Neighbourhood , Property Type, Review Scores Rating (bin), Room Type, Zipcode, Beds, Number of Records, Number Of Reviews, Price, Review Scores Rating]
Index: []

'\n\n'

In [15]:
# 2
# Categorical variable: For the Minnesota police use of for data, ./data/mn_police_use_of_force.csv, clean the subject_injury variable, handling the NA's;
# this gives a value Yes when a person was injured by police, and No when no injury occurred.
# What proportion of the values are missing? Is this a concern?
# Cross-tabulate your cleaned subject_injury variable with the force_type variable.
# Are there any patterns regarding when the data are missing?

# Load the data
mn_police = pd.read_csv("https://raw.githubusercontent.com/dylanmulieri/wrangling/refs/heads/main/assignment/data/mn_police_use_of_force.csv")

# Create copy
mn_police_df = mn_police.copy()

# Explore data
display(mn_police_df.head())
display(mn_police_df.info())
display(mn_police_df.describe())

# Look at and clean 'subject_injury variable
display(mn_police_df['subject_injury'].head())
display(mn_police_df['subject_injury'].isna().sum()) # There are 9848 NA values
# What percent of 'subject_injury' data is NA
display(mn_police_df['subject_injury'].isna().sum() / len(mn_police_df['subject_injury'])) # About 76%

# So much data is missing from thsi column that it cannot be reasonably cleaned or used with predictive power

# Cross-tabulate 'subject_injury' with 'force_type'
display(pd.crosstab(mn_police_df['subject_injury'], mn_police_df['force_type']))

'''
From the cross-tabulation we can gather:
subjects were more likely to be injured than not for Baton, Bodily Force, Gun Point Display, Improvised Weapon, Less Lethal Projectile, Police K9 Bite, and Taser
Subjects were more likely not to be injured than to be injured for Chemical Irritant and Firearm
Note that these conclusions are near meaningless with about 3 quarters of the data missing.
'''

,response_datetime,problem,is_911_call,primary_offense,subject_injury,force_type,force_type_action,race,sex,age,type_resistance,precinct,neighborhood
0,2016/01/01 00:47:36,Assault in Progress,Yes,DASLT1,NaN,Bodily Force,Body Weight to Pin,Black,Male,20.0,Tensed,1,Downtown East
1,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,Black,Female,27.0,Verbal Non-Compliance,1,Downtown West
2,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,White,Female,23.0,Verbal Non-Compliance,1,Downtown West
3,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West
4,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12925 entries, 0 to 12924
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   response_datetime  12925 non-null  object
 1   problem            12925 non-null  object
 2   is_911_call        12925 non-null  object
 3   primary_offense    12925 non-null  object
 4   subject_injury     3077 non-null   object
 5   force_type         12925 non-null  object
 6   force_type_action  12925 non-null  object
 7   race               11901 non-null  object
 8   sex                12424 non-null  object
 9   age                11859 non-null  float64
 10  type_resistance    9939 non-null   object
 11  precinct           12925 non-null  int64
 12  neighborhood       12921 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.3+ MB

None

                age      precinct
count  11859.000000  12925.000000
mean      29.484527      2.809981
std       10.987780      1.519432
min        0.000000      0.000000
25%       22.000000      1.000000
50%       28.000000      3.000000
75%       35.000000      4.000000
max       82.000000      5.000000

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: subject_injury, dtype: object

np.int64(9848)

np.float64(0.7619342359767892)

force_type,Baton,Bodily Force,Chemical Irritant,Firearm,Gun Point Display,Improvised Weapon,Less Lethal Projectile,Police K9 Bite,Taser
subject_injury,,,,,,,,,
No,0,1093,131,2,33,34,1,2,150
Yes,2,1286,41,0,44,40,2,44,172

In [ ]:
# 3
# Dummy variable: For the pretrial data covered in the lecture, clean the WhetherDefendantWasReleasedPretrial variable as well as you can,
# and, in particular, replace missing values with np.nan.

# load the data
pretrial = pd.read_csv("")

**Q2.** Go to https://sharkattackfile.net/ and download their dataset on shark attacks.

1. Open the shark attack file using Pandas. It is probably not a csv file, so `read_csv` won't work.
2. Drop any columns that do not contain data.
3. Clean the year variable. Describe the range of values you see. Filter the rows to focus on attacks since 1940. Are attacks increasing, decreasing, or remaining constant over time?
4. Clean the Age variable and make a histogram of the ages of the victims.
5. What proportion of victims are male?
6. Clean the `Type` variable so it only takes three values: Provoked and Unprovoked and Unknown. What proportion of attacks are unprovoked?
7. Clean the `Fatal Y/N` variable so it only takes three values: Y, N, and Unknown.
8. Are sharks more likely to launch unprovoked attacks on men or women? Is the attack more or less likely to be fatal when the attack is provoked or unprovoked? Is it more or less likely to be fatal when the victim is male or female? How do you feel about sharks?
9. What proportion of attacks appear to be by white sharks? (Hint: `str.split()` makes a vector of text values into a list of lists, split by spaces.)

**Q3.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?
  2. Read the introduction. What is the "tidy data standard" intended to accomplish?
  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, it’s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
  4. Read Section 2.2. How does Wickham define values, variables, and observations?
  5. How is "Tidy Data" defined in section 2.3?
  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?